# Generated by Django 5.2.10 on 2026-01-08 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0006_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_amount', models.PositiveIntegerField(help_text='Amount user needs to add to wallet')),
                ('benefit_amount', models.PositiveIntegerField(help_text='Extra benefit amount given')),
                ('description', ckeditor.fields.RichTextField()),
                ('influencer', models.BooleanField(default=False, help_text='Is this benefit only for influencers?')),
                ('influencer_time_period', models.DurationField(blank=True, help_text='Validity period for influencer benefits (e.g. 7 days)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-add_amount'],
            },
        ),
    ]
