# Generated by Django 5.2.10 on 2026-01-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0007_walletbenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletbenefit',
            name='add_amount',
            field=models.PositiveIntegerField(help_text='Amount user needs to add to wallet', unique=True),
        ),
    ]
