# Generated by Django 5.2.10 on 2026-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0008_alter_walletbenefit_add_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
