# Generated by Django 5.2.10 on 2026-01-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0009_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet_benefit',
            field=models.PositiveIntegerField(default=0, help_text='Extra benefit amount given'),
        ),
    ]
