# Generated by Django 5.2.10 on 2026-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walet', '0010_wallettransaction_wallet_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
