# Generated by Django 5.2.10 on 2026-01-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0014_auto_20251223_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_out_of_stock', models.BooleanField(default=True, help_text='Show out of stock products on the app/website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
