# Generated by Django 3.1.12 on 2025-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_deliveryoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='code',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Online Payment')], max_length=20, unique=True),
        ),
    ]
