# Generated by Django 3.1.12 on 2025-12-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20251229_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryOption',
            new_name='PaymentOption',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.paymentoption'),
        ),
    ]
