# Generated by Django 3.1.12 on 2026-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20251229_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_gst',
            field=models.FloatField(default=0),
        ),
    ]
