# Generated by Django 3.1.12 on 2026-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20260102_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_gst_percentage',
            field=models.FloatField(default=0),
        ),
    ]
