# Generated by Django 3.1.12 on 2026-01-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_total_gst_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_gst_percentage',
            new_name='gst_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='gstn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
