# Generated by Django 5.2.10 on 2026-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20260102_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_benefit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
