# Generated by Django 5.2.10 on 2026-01-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_purchase_benefit_alter_paymentoption_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('qr_code', 'QR Code')], default='standard', max_length=10),
        ),
    ]
