# Generated by Django 5.2.10 on 2026-01-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='couponcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='influencer_code',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='walet_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
