# Generated by Django 5.2.10 on 2026-02-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_deliveryslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryslot',
            name='booked_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
